### ISSUE TITLE
重复文件夹

### ISSUE THREAD

**Issue by Tony-Yes** [CCCOrz/qBittorrent-rclone-sync#2]
上传会创建多个重复的文件夹，是设置问题吗
![](https://tu.kp.al/2023/10/10/%25pn_2023-10-10_13-54-18.png)
![](https://tu.kp.al/2023/10/10/%25pn_2023-10-10_13-54-46.png)
> # 挂载的磁盘 (df -h 查看 Mounted on 挂载的目录)
DISK_LOCAL="/"

# rclone挂载名称
RCLONE_NAME="gd2:"

# rclone本地挂载目录
RCLONE_LOCAL_DIR="/home/gd"

# 远程资源保存路径(以 "/" 结尾)
RCLONE_REMOTE_DIR="/media/"

**Comment by pushduck** [comment]
配置看起来没有问题，上传全部完成也不会合并吗？THREAD改成1看看

**Comment by Tony-Yes** [comment]
目前还没有下载完成 意思是全部下载完成之后会自动合并吗

**Comment by pushduck** [comment]
> 目前还没有下载完成 意思是全部下载完成之后会自动合并吗

#### 你可以按以下步骤试试：
0. 使用一键命令更新到最新版本
1. 检查新的配置文件
2. 停止本程序
3. 暂停下载
4. 删除这些重复的文件夹
5. 手动在网盘根目录创建一个media文件夹
6. 启动本程序
7. 恢复下载

**Comment by Tony-Yes** [comment]
> > 目前还没有下载完成 意思是全部下载完成之后会自动合并吗
> 
> #### 你可以按以下步骤试试：
> 0. 使用一键命令更新到最新版本
> 1. 检查新的配置文件
> 2. 停止本程序
> 3. 暂停下载
> 4. 删除这些重复的文件夹
> 5. 手动在网盘根目录创建一个media文件夹
> 6. 启动本程序
> 7. 恢复下载

程序是刚刚安装的最新版 配置文件中THREAD已修改为1 本地和网盘文件均已删除 我再试一下 有问题我再更新

**Comment by Tony-Yes** [comment]
THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了

**Comment by pushduck** [comment]
> THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了

你可以试试改大一点 要手动创建第一个文件夹

**Comment by Tony-Yes** [comment]
> > THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了
> 
> 你可以试试改大一点 要手动创建第一个文件夹

任务已经手动改成6 没有出现创建多文件夹的问题 看来是文件夹必须手动创建好

**Comment by pushduck** [comment]
> > > THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了
> > 
> > 
> > 你可以试试改大一点 要手动创建第一个文件夹
> 
> 任务已经手动改成6 没有出现创建多文件夹的问题 看来是文件夹必须手动创建好

对的 没有初始文件夹的话会同时创建THREAD个文件夹

**Comment by Tony-Yes** [comment]
> > > > THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了
> > > 
> > > 
> > > 你可以试试改大一点 要手动创建第一个文件夹
> > 
> > 
> > 任务已经手动改成6 没有出现创建多文件夹的问题 看来是文件夹必须手动创建好
> 
> 对的 没有初始文件夹的话会同时创建THREAD个文件夹

还是有点问题 文件已经传输完了 本地文件也不在了 进程还在 需要重启程序才能继续

![](https://tu.kp.al/2023/10/10/%25pn_2023-10-10_20-04-56.png)
![](https://tu.kp.al/2023/10/10/%25pn_2023-10-10_20-05-34.png)

**Comment by pushduck** [comment]
> > > > > THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了
> > > > 
> > > > 
> > > > 你可以试试改大一点 要手动创建第一个文件夹
> > > 
> > > 
> > > 任务已经手动改成6 没有出现创建多文件夹的问题 看来是文件夹必须手动创建好
> > 
> > 
> > 对的 没有初始文件夹的话会同时创建THREAD个文件夹
> 
> 还是有点问题 文件已经传输完了 本地文件也不在了 进程还在 需要重启程序才能继续
> 
> ![](https://camo.githubusercontent.com/eb6160042732fcdfe9b577ca164fec989e34bf5b7d685640c0019b7b7b4f52fd/68747470733a2f2f74752e6b702e616c2f323032332f31302f31302f253235706e5f323032332d31302d31305f32302d30342d35362e706e67) ![](https://camo.githubusercontent.com/7da00f285f1807088cf21a5948dc208206dd2a5c2dec6f2b3553b61fe09d01fc/68747470733a2f2f74752e6b702e616c2f323032332f31302f31302f253235706e5f323032332d31302d31305f32302d30352d33342e706e67)

暂时复现不了你的情况

**Comment by Tony-Yes** [comment]
> > > > > > THREAD=1 运行正常 不会创建多个文件夹 这样似乎只能单文件上传了
> > > > > 
> > > > > 
> > > > > 你可以试试改大一点 要手动创建第一个文件夹
> > > > 
> > > > 
> > > > 任务已经手动改成6 没有出现创建多文件夹的问题 看来是文件夹必须手动创建好
> > > 
> > > 
> > > 对的 没有初始文件夹的话会同时创建THREAD个文件夹
> > 
> > 
> > 还是有点问题 文件已经传输完了 本地文件也不在了 进程还在 需要重启程序才能继续
> > ![](https://camo.githubusercontent.com/eb6160042732fcdfe9b577ca164fec989e34bf5b7d685640c0019b7b7b4f52fd/68747470733a2f2f74752e6b702e616c2f323032332f31302f31302f253235706e5f323032332d31302d31305f32302d30342d35362e706e67) ![](https://camo.githubusercontent.com/7da00f285f1807088cf21a5948dc208206dd2a5c2dec6f2b3553b61fe09d01fc/68747470733a2f2f74752e6b702e616c2f323032332f31302f31302f253235706e5f323032332d31302d31305f32302d30352d33342e706e67)
> 
> 暂时复现不了你的情况

有什么办法debug吗 任务其实已经完成 但是程序内进度没变 tg通知上一直刷新 进度都是10%左右 服务器上查到进程还在 
![SmartSelect_20231011_111656_Nekogram](https://github.com/durianice/qBittorrent-rclone-sync/assets/72665660/95fc1044-825b-47c1-afb9-eca20b368dc8)

**Comment by pushduck** [comment]
> 有什么办法debug吗 任务其实已经完成 但是程序内进度没变 tg通知上一直刷新 进度都是10%左右 服务器上查到进程还在 ![SmartSelect_20231011_111656_Nekogram](https://user-images.githubusercontent.com/72665660/274131204-95fc1044-825b-47c1-afb9-eca20b368dc8.jpg)

看看这个日志 /root/qbit_rclone_sync.log 有内容说明确实正在同步

**Comment by Tony-Yes** [comment]
> > 有什么办法debug吗 任务其实已经完成 但是程序内进度没变 tg通知上一直刷新 进度都是10%左右 服务器上查到进程还在 ![SmartSelect_20231011_111656_Nekogram](https://user-images.githubusercontent.com/72665660/274131204-95fc1044-825b-47c1-afb9-eca20b368dc8.jpg)
> 
> 看看这个日志 /root/qbit_rclone_sync.log 有内容说明确实正在同步

是在同步的 但是任务已经完成了 这个进度跟不上实际的 等很久都没同步完 后面任务跟不上 重启程序之后才会继续
