### ISSUE TITLE
最好能在配置里指定下载上传路径

### ISSUE THREAD

**Issue by lulexyz** [CCCOrz/qBittorrent-rclone-sync#3]
我是用docker安装的qbittorrent，qbrs无法上传文件。分析可能是获取的下载路径不对。

**Comment by pushduck** [comment]
文件映射成一样的

**Comment by Benson80** [comment]
docker run -d \
    --name=qbittorrentee  \
    -e WEBUIPORT=8080  \
    -e PUID=1026 \
    -e PGID=100 \
    -e TZ=Asia/Shanghai \
    -p 6881:6881  \
    -p 6881:6881/udp  \
    -p 8080:8080  \
    -v /qbittorrent:/config  \
    -v /downloads:/downloads  \
    --restart unless-stopped  \
    superng6/qbittorrentee:latest
映射成同样的目录还是无法上传！

**Comment by pushduck** [comment]
> docker run -d --name=qbittorrentee -e WEBUIPORT=8080 -e PUID=1026 -e PGID=100 -e TZ=Asia/Shanghai -p 6881:6881 -p 6881:6881/udp -p 8080:8080 -v /qbittorrent:/config -v /downloads:/downloads --restart unless-stopped superng6/qbittorrentee:latest 映射成同样的目录还是无法上传！

你看看docker启动的qbittorrent下载目录是啥，再看看对应的宿主机有没有相应目录。

**Comment by pushduck** [comment]
QBIT_DIR=""

> 我是用docker安装的qbittorrent，qbrs无法上传文件。分析可能是获取的下载路径不对。

新增了配置 QBIT_DIR 配置文件加一下路径就好 这个优先级最高 设置了这个路径就不会读下载器的路径设置了

**Comment by pushduck** [comment]
> docker run -d --name=qbittorrentee -e WEBUIPORT=8080 -e PUID=1026 -e PGID=100 -e TZ=Asia/Shanghai -p 6881:6881 -p 6881:6881/udp -p 8080:8080 -v /qbittorrent:/config -v /downloads:/downloads --restart unless-stopped superng6/qbittorrentee:latest 映射成同样的目录还是无法上传！

已添加自定义下载目录 请使用一键脚本更新
