### ISSUE TITLE
有不有可能实现不是使用rclone上传？

### ISSUE THREAD

**Issue by owo10086** [CCCOrz/qBittorrent-rclone-sync#4]
因为想挂载上传115，rclone不支持上传。然后我用cd2挂载的，请问大佬能不能实现用本地路径来上传呢？

**Comment by pushduck** [comment]
> 因为想挂载上传115，rclone不支持上传。然后我用cd2挂载的，请问大佬能不能实现用本地路径来上传呢？

计划有空会支持 请关注变更
