### ISSUE TITLE
获取message_id失败

### ISSUE THREAD

**Issue by zephyr-y** [CCCOrz/qBittorrent-rclone-sync#5]
Dec 18 20:42:08 HKG-efz qbrs_amd64[1421]: 😓 文件不在了或者目录为空，下一个
Dec 18 20:42:09 HKG-efz qbrs_amd64[1421]: 获取message_id失败： key 'result' not found

请问是哪里有错误呢？

**Comment by pushduck** [comment]
可以忽略的 不影响使用
